# Generated by Django 4.1.7 on 2023-04-03 03:10

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.functions.text
import django_enum.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Card",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("first_edition", models.BooleanField(blank=True, null=True)),
                (
                    "rarity",
                    django_enum.fields.EnumCharField(
                        blank=True,
                        choices=[
                            ("common", "Common"),
                            ("uncommon", "Uncommon"),
                            ("rare", "Rare"),
                        ],
                        max_length=8,
                        null=True,
                    ),
                ),
                ("hp", models.PositiveIntegerField(blank=True, null=True)),
                ("card_number", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                ("image", models.ImageField(blank=True, null=True, upload_to="img")),
                ("created", models.DateField(auto_now_add=True)),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="Expansion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("series", models.CharField(max_length=100)),
                ("cards", models.IntegerField(blank=True, null=True)),
                ("release_date", models.DateField(blank=True, null=True)),
                ("promotional_set", models.BooleanField(blank=True, null=True)),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="PokemonType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "resistant_to",
                    models.ManyToManyField(
                        blank=True, related_name="resists", to="api.pokemontype"
                    ),
                ),
                (
                    "strong_vs",
                    models.ManyToManyField(
                        blank=True, related_name="strong_versus", to="api.pokemontype"
                    ),
                ),
                (
                    "vulnerable_to",
                    models.ManyToManyField(
                        blank=True, related_name="vulnerable", to="api.pokemontype"
                    ),
                ),
                (
                    "weak_vs",
                    models.ManyToManyField(
                        blank=True, related_name="weak_versus", to="api.pokemontype"
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.AddConstraint(
            model_name="expansion",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("name"),
                django.db.models.functions.text.Lower("series"),
                name="unique_expansion_name_series",
            ),
        ),
        migrations.AddField(
            model_name="card",
            name="expansion",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="expansion",
                to="api.expansion",
            ),
        ),
        migrations.AddField(
            model_name="card",
            name="type1",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="type1",
                to="api.pokemontype",
            ),
        ),
        migrations.AddField(
            model_name="card",
            name="type2",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="type2",
                to="api.pokemontype",
            ),
        ),
        migrations.AddConstraint(
            model_name="pokemontype",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("name"), name="unique_type_name"
            ),
        ),
        migrations.AddConstraint(
            model_name="card",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("name"), name="unique_card_name"
            ),
        ),
    ]
